### ISSUE TITLE
Can't import

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [tommybuonomo/creative-viewpager#1]
I got this :

![image](https://user-images.githubusercontent.com/5357526/41510779-df3464a4-7272-11e8-9a24-78f84c4af217.png)

**Comment by tommybuonomo** [comment]
Hi again @AndroidDeveloperLB ,
You can't import a library folder with Android Studio because it's not an app. You have to create an Android project which import this library as a dependency in your build.gradle.
I will provide a sample folder for this library soon.

Thanks for your contribution.

**Comment by AndroidDeveloperLB** [comment]
So how can I try it out?
And what's on the animation of the repository, if not the sample?

**Comment by AndroidDeveloperLB** [comment]
Thank you.
The sample looks great, but on landscape it's being cut:
![image](https://user-images.githubusercontent.com/5357526/41841300-97f2152e-7870-11e8-9b51-c0409353ff58.png)

**Comment by AndroidDeveloperLB** [comment]
BTW, how did you do the animation on the repository?

**Comment by tommybuonomo** [comment]
Using Blender, with a [3D model of smartphone](https://free3d.com/3d-models/smartphone) and a [plugin](http://www.motionsix.co.uk/how-to-import-image-as-planes-in-blender/) to import a video as a 3D plane.

**Comment by AndroidDeveloperLB** [comment]
Nice. Did it take a long time?
I think you've missed it a bit. The left side of the smartphone seems to have black content...
And the screen content seem a bit too far from the display itself.

**Comment by tommybuonomo** [comment]
It took me about 2 hours. For the left side, yeah the shadow of the plan applies on the phone because of the incurved borders of the smartphone model. I've improved this problem on the [dots indicator](https://github.com/tommybuonomo/dotsindicator) repository, where the 3D plane don't emmit any shadow on the smartphone.

**Comment by AndroidDeveloperLB** [comment]
OK thanks. 
Have you reproduced the issue of landscape?
